const types = {
  CHANGE_THEME: 'CHANGE_THEME',
  TOGGLE_NAVBAR: 'TOGGLE_NAVBAR',
  INITIALIZE_BOARD: 'INITIALIZE_BOARD',
  SET_BOARD_NAMES: 'SET_BOARD_NAMES',
  SELECT_BOARD: 'SELECT_BOARD',
  SET_REF: 'SET_REF',
  TOGGLE_SUBTASK: 'TOGGLE_SUBTASK',
  CHANGE_TASK_COLUMN: 'CHANGE_TASK_COLUMN'
};

export default types;
