const types = {
  CHANGE_THEME: 'CHANGE_THEME',
  TOGGLE_NAVBAR: 'TOGGLE_NAVBAR',
  INITIALIZE_BOARDS: 'INITIALIZE_BOARDS',
  SELECT_BOARD: 'SELECT_BOARD',
  SET_REF: 'SET_REF'
};

export default types;
